import React, { useState } from 'react';
import { StyleSheet, View } from 'react-native';
import { Card, Text, Button, TextInput, Divider } from 'react-native-paper';

const BACKGROUND = '#0B1020';

type Match = {
  driver: string;
  riders: string[];
  pickupWindow: string;
  farePerPerson: number;
  strategyVersion: string;
};

const MOCK_MATCH: Match = {
  driver: 'Fatima (driver)',
  riders: ['You', 'Omar', 'Lina'],
  pickupWindow: '08:10–08:20',
  farePerPerson: 8.5,
  strategyVersion: 'v3.1 – route-first clustering',
};

export function TripScreen() {
  const [origin, setOrigin] = useState('');
  const [destination, setDestination] = useState('');
  const [arrivalTime, setArrivalTime] = useState('');
  const [match, setMatch] = useState<Match | null>(null);

  const handleFindMatch = () => {
    setMatch(MOCK_MATCH);
  };

  const handleAccept = () => {
    console.log('Accepted match');
  };

  const handleReject = () => {
    console.log('Rejected match');
    setMatch(null);
  };

  return (
    <View style={styles.container}>
      <Text variant="headlineMedium" style={styles.title}>
        Request a carpool
      </Text>
      <Card style={styles.card} mode="elevated">
        <Card.Content style={styles.cardContent}>
          <TextInput
            label="Origin"
            value={origin}
            onChangeText={setOrigin}
            placeholder="Dubai Marina"
            mode="outlined"
            style={styles.input}
          />
          <TextInput
            label="Destination"
            value={destination}
            onChangeText={setDestination}
            placeholder="Dubai Internet City"
            mode="outlined"
            style={styles.input}
          />
          <TextInput
            label="Desired arrival time"
            value={arrivalTime}
            onChangeText={setArrivalTime}
            placeholder="08:30"
            mode="outlined"
            style={styles.input}
          />
          <Button mode="contained" onPress={handleFindMatch} style={styles.button}>
            Find carpool match
          </Button>
        </Card.Content>
      </Card>

      {match && (
        <Card style={styles.card} mode="elevated">
          <Card.Content style={styles.cardContent}>
            <Text variant="titleMedium" style={styles.matchTitle}>
              Suggested Match
            </Text>
            <Divider style={styles.divider} />
            <Text style={styles.label}>Driver</Text>
            <Text style={styles.value}>{match.driver}</Text>
            <Text style={styles.label}>Riders</Text>
            <Text style={styles.value}>{match.riders.join(', ')}</Text>
            <Text style={styles.label}>Pickup window</Text>
            <Text style={styles.value}>{match.pickupWindow}</Text>
            <Text style={styles.label}>Fare per person</Text>
            <Text style={styles.value}>{match.farePerPerson.toFixed(1)} AED</Text>
            <Text variant="bodySmall" style={styles.caption}>
              Generated by Matching Agent · {match.strategyVersion}
            </Text>
            <View style={styles.actions}>
              <Button mode="contained" onPress={handleAccept} style={styles.acceptBtn}>
                Accept
              </Button>
              <Button mode="outlined" onPress={handleReject} style={styles.rejectBtn}>
                Reject
              </Button>
            </View>
          </Card.Content>
        </Card>
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: BACKGROUND,
    paddingHorizontal: 16,
    paddingTop: 48,
  },
  title: {
    color: '#F0F2F5',
    marginBottom: 24,
  },
  card: {
    backgroundColor: '#151A30',
    borderRadius: 16,
    marginBottom: 16,
  },
  cardContent: {
    paddingVertical: 16,
  },
  input: {
    marginBottom: 12,
    backgroundColor: '#1E2440',
  },
  button: {
    marginTop: 8,
  },
  matchTitle: {
    color: '#F0F2F5',
    marginBottom: 8,
  },
  divider: {
    marginVertical: 12,
    backgroundColor: '#2A3050',
  },
  label: {
    color: '#B0B4BC',
    fontSize: 12,
    marginTop: 8,
  },
  value: {
    color: '#F0F2F5',
    marginBottom: 4,
  },
  caption: {
    color: '#888',
    marginTop: 12,
    marginBottom: 16,
  },
  actions: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 8,
  },
  acceptBtn: {
    flex: 1,
  },
  rejectBtn: {
    flex: 1,
  },
});
